### ISSUE TITLE
Official CatMAP logo

### ISSUE THREAD

**Issue by mhoffman** [ajmedford/catmap#31]
I cannot find the CatMAP logo anywhere for download? Is there one available for use in presentations and such?

**Comment by montoyjh** [comment]
Hey Max,

I'm not sure whether there's one published online or not, but here's a copy
AJ sent me a while back.

-Joey

[image: Inline image 1]

**Comment by mhoffman** [comment]
Your attachment did not make it back onto the github issue. You could maybe send it in a different email or ideally someone could add it somewhere to the beginning of the wiki accessible for everyone?

**Comment by ajmedford** [comment]
The "official" logo is attached here. 
![catmap_logo](https://cloud.githubusercontent.com/assets/5445522/6660427/f385b8f8-cb55-11e4-8221-cb5b12214137.png)

I will also add it to the wiki - maybe a .pdf version if it will let me.
