### ISSUE TITLE
Feature request: reference website

### ISSUE THREAD

**Issue by mhoffman** [ajmedford/catmap#33]
For 'advanced beginners' it would be really useful to have a single website for an as complete as possible class, function, and attribute level documentation on a single reference website. I'll just throw [this example]( http://kmos.readthedocs.org/en/latest/reference/index.html) out there as how this could look like. The advantage of this is that one can simply Ctrl+F for a certain feature and immediately glean from it in which file or submodule to look.

Keeping such a reference is made easy both initially and maintaining it as well. And I briefly outline the steps required:

1. open an account on https://readthedocs.org/accounts/signup/
1. create stub files for each submodule in a documentation folder for sphinx.autodoc
1. create a webhook inside the github repository which triggers in generation of the HTML documentation on each merge into e.g. the master branch.

If @ajmedford would initiate step 1. & 3. I will be more than happy to contribute step 2., maybe next Wednesday?

**Comment by ajmedford** [comment]
This sounds like a great idea. I will get it set up before we meet next Wednesday.

**Comment by mhoffman** [comment]
Oh, wow, seems like idea has been picked up. So much [docs to read](http://catmap.readthedocs.org/en/latest/). Everybody who comes across it: please feel free to submit pull requests for docstrings and such. More about writing strings for Sphinx and be found [here](http://sphinx-doc.org/)
