### ISSUE TITLE
Positional order of intermediate terms

### ISSUE THREAD

**Issue by mhoffman** [ajmedford/catmap#34]
One question regarding the positional order of intermediate terms: when you define a reaction expression like (A <-> B -> C)
and each intermediate involves exactly two sites (say a1_s1 + a2_s2 <-> b1_s1 + b2_s2 -> c1_s1 + c2_s2), then is it correct to assume that CatMAP models are defined such that the order between intermediate terms is consistent? Even if s1 == s2? 

For example if the CatMAP input contains 'CO_s + O_s -> CO-O_s + *_s', does that imply that after the step has occurred the CO-O species will sit where the CO species used to be? Or is that a wrong assumption?

**Comment by chuanshi** [comment]
in a mean-field model, all sites of a given type ( _s in this case) are
indistinguishable, so I believe that means that assumption would be correct?
